apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: devops-tools
spec:
  serviceAccountName: jenkins-sa
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-home
  restartPolicy: Never
  volumes:
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: jenkins-pv-claim
