apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command: ['cat']
    tty: true
    volumeMounts:
    - mountPath: /root/.m2
      name: m2-home
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - sleep
    args:
      - 99d
  restartPolicy: Never
  volumes:
  - name: m2-home
    persistentVolumeClaim:
      claimName: jenkins-pv-claim-m2
