apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command: ['cat']
    tty: true
    volumeMounts:
      - mountPath: /home/jenkins/agent/.m2
        name: m2-home
  volumes:
  - name: m2-home
    persistentVolumeClaim:
      claimName: jenkins-pv-claim-m2
